[package]
name = "ryvus-core"
version = "0.1.0"
edition = "2024"

[dependencies]

async-trait = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true }
rand = "0.9.2"
chrono = { version = "0.4", features = ["serde"] }
